fnplus/interview-techdev-guide

- Company Specific Interview Questions/Airbnb/Solutions/Java/TwoSum.java
> Added solution #19

- CONTRIBUTORS.md
Reverts fnplus/interview-techdev-guide#22
Not following the guidelines...
> Revert "Create CONTRIBUTORS.md"

- Algorithms/Searching & Sorting/QuickSort/QuickSort.java
This adds QuickSort Algorithm which return the concatenation of the quicksorted list of elements that are less than or equal to the pivot, the pivot, and the quicksorted list of elements that are greater than the pivot.
Closes: https://github.com/fnplus/interview-techdev-guide/issues/12
> QuickSort.java

- Algorithms/Searching & Sorting/Merge Sort/merge_sort.c
> Added merge sort in C

- Algorithms/Searching & Sorting/Depth First Search in Java/DFS.java
Java implementation of DFS. It is related to issue https://github.com/fnplus/interview-techdev-guide/issues/41.
> Depth First Search in Java added

- Algorithms/Searching & Sorting/Selection Sort/selectionsort.py
This adds Selection Sort Algorithm which returns the sorted list of elements by placing the minimum element at first position, second minimum at second position and so on.
Closes https://github.com/fnplus/interview-techdev-guide/issues/34
> selectionsort.py: Add Selection Sort Algorithm 

- Algorithms/Searching & Sorting/QuickSort/quicksort.java
This adds QuickSort Algorithm which return the concatenation of the
quicksorted list of elements that are less than or equal to the pivot, the
pivot, and the quicksorted list of elements that are greater than the pivot.
Closes #25
> quicksort.c: Add QuickSort Algorithm

- Algorithms/Searching & Sorting/Binary Search/binary_search.c
- Algorithms/Searching & Sorting/Radix Sort/radix_sort.c
This PR includes Radix sort and recursive binary search implemented using C. For radix sort, some pre-populated data has been assumed. Closes the issue #51 #52
> Added radix sort and binary search in C

- Algorithms/Searching & Sorting/Merge Sort/mergeSort.cpp
This adds Merge Sort Algorithm which uses Divide and Conquer approach to sort an array by dividing the array recursively until its divided into groups of two, then sort them by swapping and then perform merging during the backtracking phase.
Closes https://github.com/fnplus/interview-techdev-guide/issues/27
> mergeSort.cpp: Add Merge Sort Algorithm 

- Algorithms/Graph Traversal/Depth First Search/dfs.cpp
- Algorithms/Graphs/Depth First Search/CPP/dfs.cpp
This adds Depth First Search(DFS) algorithm for undirected and connected graph and returns an array in of nodes according to the traversal order
Closes https://github.com/fnplus/interview-techdev-guide/issues/40
> dfs.cpp: Add Depth First Search Algorithm 

- Algorithms/Graph Traversal/Breadth First Search/bfs.cpp
- Algorithms/Graphs/Breadth First Search/CPP/bfs.cpp
This adds Breadth First Search(BFS) algorithm for undirected and connected graph and returns  an array of nodes according to the bfs traversal order
Closes https://github.com/fnplus/interview-techdev-guide/issues/37
> bfs.cpp: Add Breadth First Search Algorithm 

- Algorithms/Searching & Sorting/Merge Sort/MergeSort.java
Commit merge sort for Issue #28
> Added merge sort java

- Algorithms/Graph Traversal/Breadth First Search/BreadthFirstSearch.py
- Algorithms/Graph Traversal/Depth First Search/DepthFirstSearch.py
In reference to issue #39 & #42 ;added Breadth & Depth first search in python
> Added depth first search,Breadth first Search in python

- Algorithms/Graphs/Breadth First Search/Java/BreadthFirstSearch.java
This adds Java implementation of BFS algorithm to traverse a graph.
Starting from the root node, this algorithm explores neighboring nodes
and keeps track of visited nodes using queue data structure
to make sure no node is visited more than once.
Closes https://github.com/fnplus/interview-techdev-guide/issues/38
> BreadFirstSearch.java: Add BFS algorithm

- Algorithms/Searching & Sorting/Linear Search/linear_search.c
This PR implements linear search algo in C. closes issue #56
> Added linear search in C

- Data Structures/Stack/C/stack.c
A stack is an abstract data type that serves as a collection of elements, with two principal operations:
*  push, which adds an element to the collection, and
*  pop, which removes the most recently added element that was not yet removed.
Closes: #10
> stack.c: Add Stack using C

- Data Structures/Disjoint Sets/CPP/disjoint_sets.cpp
This adds Disjoint Sets Data Structure that keeps track of a set of elements partitioned into a number of disjoint (non-overlapping) subsets.
Closes #99
> disjoint_sets.cpp: Add Disjoint Sets Data Structure

- Data Structures/Singly Linked List/Java/SinglyLinkedList.java
This adds SinglyLinkedList Data Structure which
contains the definition of a list with the following operations: append, prepend, add, get, set, delete, getSize, isEmpty
Closes https://github.com/fnplus/interview-techdev-guide/issues/87
> SinglyLinkedList.java Add SinglyLinkedList Data Structure

- Algorithms/Graph Traversal/Depth First Search/dfs.c
> Added dfsc code

- BinarySearchRecursive.cpp
I have added the code for Binary Search using Recursion implemented in the C programming language. The code has successfully run in Dev C++ compiler. It has solved issue #65.
Please review.
Thanks.
> Binary Search - Recursive method

- .vscode/settings.json
- Algorithms/Maths/Fibonacci series/Python/Fibonnacci.py
- Algorithms/Tree Traversal/In-Order Traversal/inorder.py
- Algorithms/Tree Traversal/Post-Order Traversal/postorder.py
- Algorithms/Tree Traversal/Pre-Order Traversal/Preorder.py
- Algorithms/Tree/In-Order Traversal/Python/inorder.py
- Algorithms/Tree/Post-Order Traversal/Python/postorder.py
- Algorithms/Tree/Pre-Order Traversal/Python/Preorder.py
I have worked on tree traversal and Fibonacci.
I have read the guidelines but not able to understand how all of this works.
> Hacktoberfest 19

- Data Structures/Stack/Java/Stack.java
This adds Stack Data Structure with the pop and push features.
Closes https://github.com/fnplus/interview-techdev-guide/issues/72
> stack.java: Add Stack Data Structure

- Data Structures/Dynamic Array/CPP/dynamic_array.cpp
Dynamic memory allocation refers to allocation of memory manually by programmer. Dynamically allocated memory is allocated on Heap and non-static and local variables get memory allocated on Stack.
> dynamic_array.cpp: Add Dynamic Array

- Algorithms/Maths/Fibonacci series/BASH/Fibonacci.sh
- Algorithms/Maths/Pallindrome number/Python/Pallindrome_number.py
- Algorithms/Searching & Sorting/Counting Sort/Ruby/Counting_sort.rb
> Counting sort ruby

- Algorithms/Maths/Fibonacci series/BASH/Fibonacci.sh
- Algorithms/Maths/Pallindrome number/Python/Pallindrome_number.py
> Pallindrome number python

- Algorithms/Maths/Fibonacci series/BASH/Fibonacci.sh
> Fibonacci series bash

- Algorithms/Maths/Euclidean GCD/CPP/euclidean_gcd.cpp
- Algorithms/Maths/Fibonacci series/CPP/fibonacci_series.cpp
This PR implements Euclidean GCD for 'n' numbers in C++. As input, it takes n inputs and returns gcd as output. closes #67 #68
> added euclidean gcd of 'n' numbers and fibonacci series(using dp) in C++

- Algorithms/Maths/Euclidean GCD/Python/euclidean_gcd.py
This adds the Euclidean algorithm for computing the greatest common
divisor (GCD) of two natural numbers, the largest number that divides
both of them without leaving a remainder.
Closes https://github.com/fnplus/interview-techdev-guide/issues/142
> [Algorithm] Euclidean GCD [Python]

- Algorithms/Maths/Euclidean GCD/Java/EuclideanGCD.java
This adds the Euclidean algorithm for computing the greatest common
divisor (GCD) of two natural numbers, the largest number that divides
both of them without leaving a remainder.
Closes https://github.com/fnplus/interview-techdev-guide/issues/139
> [Algorithm] Euclidean GCD [Java]

- Algorithms/Graph Traversal/Breadth First Search/bfs.c
Breadth First Search is an algorithm used to search the Tree or Graph. BFS search starts from root node then traversal into next level of graph or tree and continues, if item found it stops other wise it continues.
Closes #35
> bfs.c: Add BFS

- Algorithms/Searching & Sorting/Bubble Sort/bubble_sort.py
> adds optimized bubble sort

- Algorithms/Searching & Sorting/Binary Search/binary_search_iter.c
- Data Structures/Queue/Python/queue.py
Implemented Binary Search Iterative Method in C #65
> binary_search_iter.c: Add Binary Search Iterative in C

- Algorithms/Maths/Euclidean GCD/C/GCD.c
> Worked on [Algorithm] Euclidean GCD [C] #144

- Algorithms/Maths/Euclidean GCD/C/Euclidean_GCD_using_Recursion.c
- Algorithms/Maths/Euclidean GCD/C/readme.md
> Euclidean GCD using Recursion with Explaination

- Data Structures/Heap/Python/Heap.py
Heap.py Add heap datastructure code
A heap, in the context of data structure, is a tree-based data structure that satisfies the heap property. The lower value key always has a parent node with a higher-value key. This is called a max-heap structure. The higher value key always has a parent node with a lower-value key. This is called a min-heap structure. Both min and max heap are implemented in this PR
closes:[DS]Heap[Python] #152
> Added Heap in python

- Data Structures/Doubly Linked List/C/doubly_linked_list.c
* Implemented doubly linked list data structures in C
* The programs demonstrates all insertion functionality of a doubly linked list.
* I have tested the code using basic test program
https://github.com/fnplus/interview-techdev-guide/issues/101
> Added doubly linked list DS

- Algorithms/Searching & Sorting/Binary Search/Binary_Search.py
Binary search divides the list recursively into 2 halves until the key element is found or the entire list is exhausted
Closes #167
> Python program to perform Binary Search

- Algorithms/Maths/Perfect number/Python/Perfect_Number.py
Python program to find Perfect numbers
Closes #173
> Python program to find Perfect numbers

- Algorithms/Graph Traversal/Kruskals Algorithms/kruskals_algorithm.cpp
This adds Kruskal's Algorithm, a minimum-spanning-tree algorithm, which finds an edge of the least possible weight that connects any two trees in the forest. It is a greedy algorithm in graph theory as it finds a minimum spanning tree for a connected weighted graph adding increasing cost arcs at each step.
Closes #181
> kruskals_algorithm.cpp: Add Kruskal's Algorithm

- Algorithms/Maths/Perfect number/Python/Perfect_Number.py
- Algorithms/Searching & Sorting/Counting Sort/Java/CountingSort.java
- Algorithms/Searching & Sorting/Insertion Sort/InsertionSort.java
This adds InsertionSort.
The array is searched sequentially and unsorted items are moved and inserted into the sorted sub-list
https://github.com/fnplus/interview-techdev-guide/issues/195
> InsertionSort.java Add InsertionSort Algorithm

- Algorithms/Maths/Perfect number/Python/Perfect_Number.py
- Algorithms/Searching & Sorting/Counting Sort/Java/CountingSort.java
This adds CountingSort which sorts a list of integers by counting them
https://github.com/fnplus/interview-techdev-guide/issues/196
> CountingSort.java Add CountingSort Algorithm

- Data Structures/Queue/C/queue.c
- Data Structures/Queue/C/readme.md
queue.c Add Queue data structure .
Implementing this queue using array (Static Implementation) . Queue is a linear data structure where the first element is inserted from one end called REAR and deleted from the other end called as FRONT. Front points to the beginning of the queue and Rear points to the end of the queue.
Queue follows the FIFO (First - In - First Out) structure.
closes PR #199
Thanks @ruudhaya @deepakgangore @fmachado091 @Amal-David @arjunmahishi
> Adding queue data structure using c and its relative readme file

- Selection Sort in C
I have created Selection Sort in C language
> Create Selection Sort in C Issue # 31

- Algorithms/Maths/Fibonacci series/Java/Fibonacci.java
> Fibonacci.java

- Algorithms/Graph Traversal/Bellman Ford Algorithm/bellman_ford_algorithm.cpp
- Algorithms/Graph Traversal/Dijkstra's Algorithm/dijkstras_algorithm.cpp
This adds Bellman Ford algorithm that computes shortest paths from a single source vertex to all of the other vertices in a weighted digraph. The graph may contain negative weight edges.
Closes #105
> bellman_ford_algorithm.cpp: Add Bellman Ford Algorithm

- Algorithms/Graphs/Topological Sort/CPP/TopologicalSort.cpp
> Added Topological Sort Algorithm in C++.

- Algorithms/Maths/Pallindrome number/CPP/palindrome.cpp
#228 
Added new file palindrome
> Added palindrome number in C++

- Algorithms/Graph Traversal/Prim's Algorithms/Prims.c
Prims Algorithm
It is a greedy algorithm . At every step, it considers all the edges that connect the two sets, and picks the minimum weight edge from these edges. After picking the edge, it moves the other endpoint of the edge to the set containing MST.
#231
> Prims Algorithm

- Algorithms/Searching & Sorting/Bubble Sort/BubbleSort.py
This adds BubbleSort Algorithm which sort the elements of an array in
place.
Closes [issues#98](https://github.com/fnplus/interview-techdev-guide/issues/98)
> bubble_sort.py Add BubbleSort Algorithm in Python

- Data Structures/Stack/Python/Stack.py
- Added `stack` implementation using `list` in `Python`
> added stack.py

- Data Structures/Singly Linked List/Python/SinglyLinkedList.py
- Data Structures/Singly Linked List/Python/readme.md
create simple linked list for issue #122
> Python linked list

- radix_sort.cpp
>  this is the algorthm for radix sort in c++

- Data Structures/Queue/Python/Queue.py
Adds Array and LinkedList implementation of Queue. Since Queue is a FIFO (First In First Out) Data Structure, the operations that can be performed using this python code are:
Enqueue: Insert element from front
Dequeue: Remove element from rear
Display: Enlist the queue
Closes https://github.com/fnplus/interview-techdev-guide/issues/84
> Add Array and LinkedList Implementation of Queue in python.

- Algorithms/perfectnumber.cpp
For the issue #229 
Please review and merge
> perfect Number in CPP added

- bucket_sort.cpp
> bucket_Sort in c

- Algorithms/Searching & Sorting/QuickSort/QuickSort.py
quicksort.py Add QuickSort Algorithm
This adds QuickSort Algorithm which return the concatenation of the
quicksorted list of elements that are less than or equal to the pivot, the
pivot, and the quicksorted list of elements that are greater than the pivot.
Closes https://github.com/fnplus/interview-techdev-guide/issues/29
> Added QuickSort in python

- Data Structures/Trie/Trie.cpp
**Issue Link:** https://github.com/fnplus/interview-techdev-guide/issues/155
This PR adds a trie implementation using Maps. The implementation covers the search and insert capability into trie
> [Trie] - Trie implementation using map

- Algorithms/Graph Traversal/Bellman Ford Algorithm/bellman_ford_algorithm.cpp
- Algorithms/Graph Traversal/Dijkstra's Algorithm/dijkstras_algorithm.cpp
Adding fnplus/interview-techdev-guide#261
> Adding "bellman_ford_algorithm.cpp: Add Bellman Ford Algorithm""

- Algorithms/Tree/Binary Search Tree/Python/binary_search_tree.py
This adds a binary search tree algorithm which returns list of elements in order traversal of binary search tree
closes https://github.com/fnplus/interview-techdev-guide/issues/158
> binary_search_tree.py: Added Binary Search Tree Algorithm

- Algorithms/Searching & Sorting/Binary Search/binary_search.java
binary_search.java : Add binary search Algorithm in Java
This returns the index of the searched number in the array. In the binary search the number is searched by repeatedly dividing the array i two parts.If the value of the search key is less than the item in the middle of the interval, narrow the interval to the lower half. Otherwise narrow it to the upper half. Repeatedly check until the value is found or the interval is empty.
Closes https://github.com/fnplus/interview-techdev-guide/issues/121
> add binary search algo in java

- Algorithms/Searching & Sorting/Selection Sort/selection_sort.java
selection_sort.java : Add Selection sort Algorithm in java
The selection sort algorithm sorts an array by repeatedly finding the minimum element (considering ascending order) from unsorted part and putting it at the beginning.
Closes https://github.com/fnplus/interview-techdev-guide/issues/33
> add selection sort in java

- Algorithms/Tree/Binary Search Tree/Python/deletion.py
- Algorithms/Tree/Segment Tree/Python/Segment_tree.py
> Segment tree : Updated

- Data Structures/Heap/CPP/heap.cpp
This PR implements heap in C++. Both min and max heap has been implemented in the code. The class object takes heap type as argument to decide which type heap it is. closes #103
> added heap data structure in C++

- Algorithms/Maths/armstrong number/armstrong_numbers.cpp
- armstrong_numbers.cpp
> c++ program to check armstrong number

- Algorithms/Maths/Modular Exponentiation/CPP/ModularExponentiation.cpp
Created new folder "Modular Exponentiation" in "Maths" and created directories so that solution can be added in other languages too.
Solve #256
> Added Modular Exponentiation in C++.

- Algorithms/Graph Traversal/Floyd-Warshall Algorithm/floyd_warshall.cpp
This adds floyd warhshall algorithm which is an algorithm for finding shortest paths in a weighted graph. A single execution of the algorithm will find the lengths of shortest paths between all pairs of vertices.
Closes #260
> floyd_warshall.cpp: Add Floyd Warshall Algorithm

- Company Specific Interview Questions/Airbnb/Solutions/Cpp/MergeSort.cpp
This adds Airbnb MergeSort Solution which is solved using priority_queues.
Time Complexity:- O(Nlog(N)) where N is the total number of elements in all the lists.
Closes #282
> MergeSort.cpp: Add Airbnb MergeSort Solution

- Algorithms/Arrays/Kadane/Kadane_algo.java
kadane_algo.java: Adds Kadane's Algorithm in Java
Closes #290
>  adds kadane's algo in java

- Algorithms/Maths/Magic Number/Magic Number.py
> Solves #292 : Added Magic Number soln in python

- Company Specific Interview Questions/Google/Solutions/Cpp/Word_Break.cpp
Hi @sauravjaiswalsj, Please merge **Google** Interview problem - **Word Sequence**  C++ solution.
issue is #299 
Thanks
> Google Word Sequence CPP Solution added

- Algorithms/Maths/Perfect number/Java/PerfectNumber.java
This adds the algorithm for identifying whether an integer is a perfect
number or not. A perfect number is a positive integer that is equal to
the sum of its positive divisors, excluding the number itself.
For instance, 6 has divisors 1, 2 and 3 (excluding itself), and
1 + 2 + 3 = 6, so 6 is a perfect number.
Reference: https://en.wikipedia.org/wiki/Perfect_number
Closes https://github.com/fnplus/interview-techdev-guide/issues/310
> [Algorithm] Perfect number [Java]

- Algorithms/Dynamic Programming/edit_distance.py
> [Algorithm] DP - Edit Distance [Python]

- Algorithms/Searching & Sorting/Heap Sort/heap_sort.cpp
This PR implements heap sort in C++. Closes #104
> added heap sort in C++

- Algorithms/Searching & Sorting/Bubble Sort/bubble_sort.cs
Resolves the [issue](https://github.com/fnplus/interview-techdev-guide/issues/278)
> Add bubble sort in C#

- Algorithms/sumofsubset.java
#274 Adding a program in java which determine if there is a subset of the given set with sum equal to given sum.
> [Algorithm] Sum of Subset [Java]

- Data Structures/Singly Linked List/C/singlylinkedlist.c
As per https://github.com/fnplus/interview-techdev-guide/issues/232
> Added a simple singly linked list example

- Algorithms/Arrays/Subsequence/print_subsequence.cpp
Add generating subsequence of array in C++
> Add subsequence of array

- Data Structures/Circular Linked List/Python/circular_linked_list.py
- Data Structures/Doubly Linked List/Python/doubly_linked_list.py
edit : @jenistenxavier This is the pull request prior to issue #337
> Added python implementation of doubly & circular linked list

- Data Structures/Circular Linked List/Python/circularlinkedlist.py
#337 Python program to create and display a Circular Linked List
> [Data Structure] Circular Linked List [Python]

- Data Structures/Queue/Java/StaticQueueinjava.java
> Add Queue in java

- javascript/interview-techdev-guide-master/Algorithms/Searching & Sorting/Selection Sort/selectionsort.c
i have added selectionsort in c .
closed issue #31
> edit selection sort in c

- Algorithms/Searching & Sorting/Selection Sort/SelectionSort.java
Created selection sort in java version
> selection sort created in java

- Algorithms/COMPUTATIONAL_GEOMETRY.md
- Algorithms/COMPUTATIONAL_GEOMETRY.py
- Algorithms/sieve.md
- Algorithms/sieve.py
Basically in this algorithm two end points of two line segments are taken and it checks whether the two line segments intersects or not!!
> COMPUTATIONAL GEOMETRY

- Algorithms/Maths/Perfect number/Python/Perfect_Number.py
- README.md
Enhance the perfect number algorithm
Organize code in a class.
Improve the time complexity at least by the square root of the input.
Closes https://github.com/fnplus/interview-techdev-guide/issues/338
> a more thorough implementation of perfect numbers

- Algorithms/Maths/Perfect Number/Python/perfect.py
Simple example of Perfect number made with python.
Asks for `start `and `end `bounds and print all perfect numbers in between.
As in: https://github.com/fnplus/interview-techdev-guide/issues/338
> perfect.py: Added example of Perfect Number for Python

- Algorithms/Tree/Binary Search Tree/Python/bst.py
bst.py Add Binary Search Tree Implementation
This adds the implementation of Binary Search Tree, which is a data structure, where each node has a left child node and a right child node. The first node is known as the root node. The values lesser than a particular node is added to the left child or left subtree of that particular node and the values greater than a particular node are added to the right child or right subtree of that particular node.
closes https://github.com/fnplus/interview-techdev-guide/issues/158
> Binary Search Tree in Python

- Algorithms/Maths/Magic Number/Nodejs/MagicNumber.js
added logic for Magic  number in Nodejs #292
> added logic for Magic  number 

- Algorithms/Searching & Sorting/Binary Search/binary_search_iterative_recursive.java
- Algorithms/Searching & Sorting/Insertion Sort/Insertion_sort.java
https://en.wikipedia.org/wiki/Binary_search_algorithm
This finds the position of a target value within a sorted array. It compares the target value to the middle element of the array. If it is not equal the half that the target cannot be in is 'removed' and the search continues on the remaining half, again taking the middle element to compare to the target value, repeating this till the target value is found. If the search ends with the remaining half being empty, the target is not in the array.
Solved issue - #287 
https://en.wikipedia.org/wiki/Insertion_sort
Insertion sort is an algorithm that sorts a list one item at a time. The list is split into a sorted part and non-sorted part. With each iteration, it takes the next value waiting to be sorted (in the unsorted part) and it inserts …
> Add Binary Search Iterative & Recursive & Insertion Sort - Java

- Algorithms/Searching & Sorting/Insertion Sort/InsertionSort.py
- README.md
Add insertion sort algorithm
I implemented insertion sort with python in this branch.
Closes https://github.com/fnplus/interview-techdev-guide/issues/335
> Insertion sort python

- Algorithms/Graphs/Cycle Detection/Directed Graph/CPP/cycle_detection_directed.cpp
- Algorithms/Graphs/Cycle Detection/Directed Graph/Java/cycle_detection_directed.java
- Algorithms/Graphs/Cycle Detection/Directed Graph/Python/cycle_detection_directed.py
- Algorithms/Graphs/Cycle Detection/Undirected Graph/C/cycle_detection_undirected.c
- Algorithms/Graphs/Cycle Detection/Undirected Graph/CPP/cycle_detection_undirected.cpp
- Algorithms/Graphs/Cycle Detection/Undirected Graph/Java/cycle_detection_undirected.java
- Algorithms/Graphs/Cycle Detection/Undirected Graph/Python/cycle_detection_undirected.py
Cycle Detection in undirected graph in C, C++, Java, Python using union find algorithm.
Cycle detection in directed graph in C++, Java, Python using DFS.
for https://github.com/fnplus/interview-techdev-guide/issues/279
> Detect cycle in a Graph

- Algorithms/String/KMP/CPP/KMP.cpp
> KMP Algoritham to search substring

- Algorithms/Searching & Sorting/Insertion Sort/Insertionsort.py
#335 Adding Insertion sort program in python language.
> [Algorithm] Insertion Sort [Python]

- Algorithms/Maths/Perfect Number/C/PerfectNumber.c
- Algorithms/Maths/Perfect Number/Java/PerfectNumber.java
- Algorithms/Maths/Perfect Number/Python/Perfect_Number.py
- Data Structures/Queue/Python/simple_queue.py
Add a Queue implementation in Python.  
closes #94
> simple_queue.py: Add Queue in Python

- Algorithms/Graphs/Belmon Ford Algorithm/Java/bellman_ford_algo.java
I have added the Bellman ford algorithm in Java . 
Closes #309
> added bellman ford algo in java

- Algorithms/Tree/AVL Tree/CPP/avl.cpp
- Algorithms/Tree/AVL Tree/CPP/output.txt
The changes are:
+ AVL Tree implementation in c++,i.e, Algorithms/Tree/AVL Tree/CPP/avl.cpp
+ a sample output to the above also added
This closes the issue :
https://github.com/fnplus/interview-techdev-guide/issues/367
> Avl tree implementation in C++

- Algorithms/Graph Traversal/Depth First Search/dfs.py
I will like to add another code for Depth First Search in Python
> Added other code for dfs in python

- Algorithms/Graphs/Implementation of BFS using adjacency matrix/c++/Implementation of BFS using adjacency matrix.cpp
- Algorithms/Maths/Sieve of Eratosthenes algorithm/cpp/Sieve of Eratosthenes algorithm.cpp
- Algorithms/Maths/Sieve of Eratosthenes algorithm/java/Sieve ofEratosthenes algorithm.java
> implemetation of bfs

- Data Structures/Trie/Trie.py
For #440 
@jenistenxavier @fnplus
> Add Trie implementation in Python

- Algorithms/Tree/Height of the tree/Python/height_of_bst.py
@sauravjaiswalsj This is a PR prior to issue #475
> added height of tree bst implementation python

- Data Structures/Fibonacci Heap/Python/FibonacciHeap.py
Create an instance of FibonacciHeap.The user is presented with a menu to perform various operations on the heap. The corresponding methods are called to perform each operation. 
Closes  https://github.com/fnplus/interview-techdev-guide/issues/373
> Created Fibonacci Heap.

- Company Specific Interview Questions/Airbnb/Solutions/Cpp/BinarySearchTree.cpp
This adds Airbnb BinarySearchTree problem's solution which is solved using recursion and divide and conquer.
Time Complexity:- O(N)
Closes #457
> BinarySearchTree.cpp: Add Airbnb BinarySearchTree

- Data Structures/Adjacency matrix/Python/adjacency_matrix.py
adjacency_matrix.py - Add Adjacency Matrix Data Structure
This PR implemented a class for the Adjacency Matrix. I am welcome to any comment or order for further fixes and improvements. Thank you. 
Closes https://github.com/fnplus/interview-techdev-guide/issues/374
> adjacency_matrix.py - Add adjacency matrix data structure

- Algorithms/Maths/Pallindrome number/Java/PallindromeNumber.java
This code checkes the number is palindrome or not.
> [Algorithm] Palindrome [JAVA]

- Algorithms/Maths/Pallindrome number/Python/Palindrome.py
This code checkes the number is palindrome or not.
> [Algorithm] Palindrome [Python]

- Data Structures/Doubly Linked List/C/Doubly linked list.c
Adding doubly linked list structure in C language
> Adding doubly linked list structure

- Algorithms/Searching & Sorting/Binary Search/Ruby/binary_search.rb
> Added Binary Search In Ruby

- Algorithms/Searching & Sorting/Selection Sort/selectionsort.c
Added a file for selection sort in C. I'm pretty new to open source and programming - thank you for the opportunity to contribute!
> Adding selection sort in C

- Algorithms/Tree Traversal/Binary Search Tree/BST.py
> Binary Search Tree and traversal in python

- Data Structures/Stack/Python/python_stack_implementation.py
#157
List append() and pop() functions to create into Stack implementation class in python
> [Data Structure] Stack Implementation [Python]

- Algorithms/Maths/Perfect number/C/perfect_number.c
#133
Program that checks the  given number is perfect number or not in c language.
> [Algo] Perfect Number [C]

- Data Structures/Singly Linked List/Python/linked_list.py
#122 
Creating a simple linked list in python with three nodes, traversing the created list and print the data of each node.
> [Data Structure] Singly Linked List [Python]

- Algorithms/Searching & Sorting/Selection Sort/selectionsort.cpp
selectionsort.cpp Add Selection Sort Algorithm
This adds an Selection Sort Algorithm which returns an Sorted Array 
in O(n^2) Time Complexity.
Closes - #224
> Add selectionsort.cpp 

- Algorithms/Searching & Sorting/pigeon hole sort/piegonhole.sort
- armstrong_numbers.cpp
- pure_numbers.cpp
- shell_sort.cpp
- timsort.cpp
#293 
Pigeonhole Sort
Pigeonhole sorting is a sorting algorithm that is suitable for sorting lists of elements where the number of elements and the number of possible key values are approximately the same.
It requires O(n + Range) time where n is number of elements in input array and ‘Range’ is number of possible values in array.
Working of Algorithm :
Find minimum and maximum values in array. Let the minimum and maximum values be ‘min’ and ‘max’ respectively. Also find range as ‘max-min-1’.
Set up an array of initially empty “pigeonholes” the same size as of the range.
Visit each element of the array and then put each element in its pigeonhole. An element arr[i] is put in hole at index arr[i] – min.
Start the loop all over the pigeonhole array in order and put the elements from non- …
> Pigeon hole sort

- Algorithms/Eratosthenes.cpp
Added Sieve of Eratosthenes to generate prime numbers.
The program is in c++.
This pull request is a part of my HacktoberFest 2019 attempt.
> Added Sieve of Eratosthenes to generate prime numbers

- Algorithms/Searching & Sorting/insertion.py
just ive written python code for insertion sort.
[Algo/Data Structure] Insertion Sort[Python]
Issue #346
Description: Insertion Sort Algorithm is implemented in Python.
> insertion.py added.

- Algorithms/Graph Traversal/Floyd-Warshall Algorithm/floyd_warshal.java
I have added the implementation of the All pair shortest part algorithm
Closes #353
> added floyd warshal algo in java

- Algorithms/Arrays/Mazepath/mazepath.java
Implemented the Mazepath algorithm in java with the help of 2-D array and recursion.
> Mazepath Algorithm in Java #361

- Algorithms/fibonacci.py
This adds the Algorithm to print the first n numbers in the Fibonacci Series in Python where n is the number given by the user.
Closes https://github.com/fnplus/interview-techdev-guide/issues/379
> fibonacci.py: Add Algorithm for Fibonacci Series

- Company Specific Interview Questions/Airbnb/Solutions/Cpp/Validparentheses.cpp
This adds solution for Airbnb Valid parenthesis question using stacks.
Time complexity: O(N)
Space complexity: O(N)
Closes #391
> Validparentheses.cpp: Add Airbnb Valid parenthesis

- Algorithms/Arrays/Bubble_sort/SortBubble.java
Added Bubble Sort in Arrays directory
> Added Bubble Sort Java code in Arrays Directory

- Data Structures/Stack/Python/Stack.py
This one's for Hacktoberfest.
Fixes #372
> Add Python stack implementation

- Algorithms/Arrays/Kadane/kadane_algo.cpp
- Algorithms/Arrays/Kadane/kadane_algo.py
- Algorithms/Arrays/Subsequence/print_subsequence.py
- Algorithms/Dynamic Programming/fractional_knapsack.py
- Algorithms/fibonacci.py
- Algorithms/sumofsubset.py
Added Python code for the Fractional Knapsack Problem.
> Add fractional knapsack python

- Algorithms/Tree/Height of the tree/Java/bst_height.java
- Algorithms/Tree/Height of the tree/Java/readme.md
> function for height of bst

- Algorithms/Searching & Sorting/Counting Sort/python
Added counting sort in python.
issue no. #376 
#63
> Create countingsort in python

- Algorithms/Arrays/Kadane/kadane_algo.cpp
- Algorithms/Arrays/Kadane/kadane_algo.py
- Algorithms/Arrays/Subsequence/print_subsequence.py
- Algorithms/Dynamic Programming/fractional_knapsack.py
- Algorithms/Maths/Magic Number/magic_number.c
- Algorithms/Maths/Magic Number/magic_number.cpp
- Algorithms/fibonacci.py
- Algorithms/sumofsubset.py
Added C++ code to check if a number is Magic Number or not.
> Add magic number cpp

- Algorithms/Arrays/Kadane/kadane_algo.cpp
- Algorithms/Arrays/Kadane/kadane_algo.py
- Algorithms/Arrays/Subsequence/print_subsequence.py
- Algorithms/Dynamic Programming/fractional_knapsack.py
- Algorithms/Maths/Magic Number/MagicNumber.java
- Algorithms/Maths/Magic Number/magic_number.c
- Algorithms/Maths/Magic Number/magic_number.cpp
- Algorithms/fibonacci.py
- Algorithms/sumofsubset.py
Added Java code to check if given number is Magic Number or not.
> Add magic number java

- Algorithms/Searching & Sorting/Bogo Sort/bogo.py
Please assign  this to me
This closes #433 
Description of Bogo Sort- https://en.wikipedia.org/wiki/Bogosort
> [Algorithm] Bogo Sort [Python]

- Algorithms/Searching & Sorting/Insertion Sort/Insertion-Sort.c
i added insertion Sort  to the feature
> Add some feature

- Data Structures/Priority Queue/Java/Main.java
This commit will resolve issue #220
> Add Priority Queue implementation in Java resolving #220

- Algorithms/Searching & Sorting/Shell Sort/shellsort.py
Issue was [Algorithm] Sorting array using shell sort. #446
added Shell sort Algorithm Code in Shell sort folder.
> added shell sort python program

- README.md
Closes https://github.com/fnplus/interview-techdev-guide/issues/448
> [Readme] Add DP table

- Algorithms/Tree Traversal/Binary Search Tree/Python/1.Search.py
- Algorithms/Tree Traversal/Binary Search Tree/Python/2.Insert.py
Signed-off-by: Vigneshwar Ravichandran <vigneshwarravichandran@gmail.com>
> BST changes

- Algorithms/Dynamic Programming/Fractional_Knapsack_Problem.cpp
> Fractional_knapsack_problem in cpp

- Algorithms/Searching & Sorting/Shell Sort/sort.py
Signed-off-by: Vigneshwar Ravichandran <vigneshwarravichandran@gmail.com>
> Added Shell Sort

- Algorithms/Searching & Sorting/Bogo Sort/sort.py
Signed-off-by: Vigneshwar Ravichandran <vigneshwarravichandran@gmail.com>
> Added Bogo Sort

- Algorithms/Dynamic Programming/Fractional_Knapsack_Problem.cpp
- Algorithms/Greedy Algorithm/Activity_Selection_Problem.py
- Algorithms/Greedy Algorithm/Fractional_Knapsack_Problem.cpp
- Algorithms/Greedy Algorithm/README.md
Fractional_Knapsack_Problem.cpp
> Fractional_Knapsack_Problem in Greedy Algorithm

- Company Specific Interview Questions/Amazon/Solutions/Java/LowestCommonAncestor.java
added java solution for lowesr common ancestor
> lowest common ancestor of a tree

- Algorithms/Searching & Sorting/Insertion Sort/insertion_sort_python.py
for the issue https://github.com/fnplus/interview-techdev-guide/issues/416
> Insertion sort pyhton

- Company Specific Interview Questions/Airbnb/Solutions/Cpp/TwoSum.cpp
@jenistenxavier @sauravjaiswalsj Issue: #478
Hey, 
Kindly add Hacktoberfest tag and merge my PR.
Tasks:
C++ solution
Along with explanation
> Added Airbnb TwoSum implementation in C++

- Algorithms/Tree/Height of the tree/CPP/Height of BST in C++.cpp
- Algorithms/Tree/Lowest Common Ancestor in BST/c/Lowest Common Ancestor in BST using C++.cpp
- Algorithms/Tree/Printing a Binary Tree in Vertical Order in C++/cpp/Printing a Binary Tree in Vertical Order in C++.cpp
- Algorithms/Tree/countLeafNodes/cpp/countLeafNodes.cpp
- Algorithms/Tree/deleteTree/cpp/delete a Tree.cpp
- Algorithms/Tree/deleteTree/cpp/deleteTree.cpp
- Algorithms/Tree/diameterTree/c/diameterTree.cpp
> Delete a Tree

- Algorithms/Searching & Sorting/Bubble Sort/Bubble_sort.c
Closes https://github.com/fnplus/interview-techdev-guide/issues/493
> Added Bubble Sort in C

- Algorithms/Searching & Sorting/Bubble Sort/Bubble_sort.cpp
Closes https://github.com/fnplus/interview-techdev-guide/issues/497
> Added Bubble Sort in CPP

- Algorithms/Graphs/Kruskal's Algorithm/C/kruskals.c
Closes https://github.com/fnplus/interview-techdev-guide/issues/500
> Added Kruskals Algorithm in C

- Algorithms/Graph Traversal/Bellman Ford Algorithm/bellmanford.py
Python implementation for Bellman Ford
Further work needed, for e.g predecessor list
> Closes #499

- Company Specific Interview Questions/Google/Solutions/Python/google_find_odds.md
- Company Specific Interview Questions/Google/Solutions/Python/google_find_odds.py
- Company Specific Interview Questions/Google/Solutions/Python/valid.md
- Company Specific Interview Questions/Google/Solutions/Python/valid.py
> Google Find Odds

- Algorithms/Searching & Sorting/Counting Sort/Python/counting_sort.py
> implement counting sort in python

- Algorithms/Dynamic Programming/generate_parentheses/generate_parentheses.py
This adds Generate Parentheses algoirhtm which returns the permutations of valid parentheses generated for n pairs of parentheses.
Closes https://github.com/fnplus/interview-techdev-guide/issues/510
> generate_parentheses.py Add Generate Parentheses Algorithm

- Algorithms/Searching & Sorting/Counting Sort/Counting Sort.cpp
- Algorithms/Searching & Sorting/Insertion Sort/insertion sort.cpp
> Insertion Sort in cpp

- Data Structures/Deque/Python/deque.py
This implements deque data structure using Pythin inbuilt list
Closes https://github.com/fnplus/interview-techdev-guide/issues/517
> deque.py: Add Deque Data Structure

- Algorithms/Dynamic Programming/longest_common_subsequence.py
It contains two functions
1. LCS_by_recursion
It calculates the length of the longest common subsequence using recursion. Does not return the
common subsequence
2. longest_common_subsequence
Determines the longest common subsequence using Dynamic Programming method using memoization.
This method returns the length along with the subsequence.
Doctest is also added to the code
Execution:
```
python longest_common_subsequence.py
```
> Created longest_common_subsequence file using python

- Algorithms/Maths/Euclidean GCD/C/GCD.c
- Algorithms/Maths/Euclidean GCD/C/readme.md
- Algorithms/String/run-length-encoding/readme.md
- Algorithms/String/run-length-encoding/rle.c
Efficient way of computing gcd
> use of stack and euclid algo to compute gcd

- Algorithms/Searching & Sorting/Binary Search/binary_search_iterative.py
- Algorithms/Searching & Sorting/Exponential Search/exponential_search.py
- Algorithms/Searching & Sorting/Interpolation Search/interpolation_search.py
- Algorithms/Searching & Sorting/Jump Search/jump_search.py
I have implemented a few search algorithms in python, namely:
-Iterative version of binary search, where space complexity is O(1)
-Jump Search
-Exponential Search
-Interpolation Search
> New Search Algorithms in Python

- Data Structures/Heap/C/heap.c
Created the implementation of heap using C language in the Data Structures repository
> Created heap code

- Algorithms/Dynamic Programming/Longest Common Subsequence/CPP/longestCommonSubseq.cpp
- Algorithms/Dynamic Programming/Longest Common Substring/CPP/longestCommonSubstring.cpp
- Algorithms/Dynamic Programming/Longest Increasing Subsequence/CPP/longestIncreasingSubsequence.cpp
this pr is wrt https://github.com/fnplus/interview-techdev-guide/issues/442
added
- longest common subseq
- longest common substr
- longest increasing subseq
> Basic Dynamic Programming Problems

- Data Structures/Trie/Trie.py
Handling non-alphabet user input if not between [a-z].
> Fixing Trie.py

- Algorithms/Searching & Sorting/Shell Sort/ShellSort.java
This adds ShellSort algorithms problem in java.
Closes: #579
> Created Program of ShellSort

- Data Structures/AVL Tree/Avltree.py
This adds AVL TREE algorithms problem in python.
Closes: #584
> Created AVL Tree for python

- Algorithms/Recursion/tower_of_hanoi.c
solved issue #490 : Implemented Tower of Hanoi using Recursive Function in C
> Implemented Tower of Hanoi using Recursive Function in C

- Algorithms/Tree/printLeafNodes/cpp/Print all leaf nodes of a Binary Tree from left to right.cpp
Print leaf nodes from left to right  in C++
> printLeafNodes

- Algorithms/Maths/Sieve of Eratosthenes algorithm/sieve.c
- README.md
Implementation of sieve of Eratosthenes in C
> Ft sieve of erastosthene

- Algorithms/Greedy Algorithm/Travelling_Salesman_Problem.cpp
This adds Travelling Salesman Problem which is a Greedy Algorithm used to calculate the shortest route to cover all the cities and return back to the origin city. This method is use to find the shortest path to cover all the nodes of a graph.
> Travelling_Salesman_Problem.cpp Add Greedy Algorithm

- Algorithms/Searching & Sorting/Radix Sort/Radix_Sort.cpp
> RadixSort.cpp

- Algorithms/Searching & Sorting/BucketSort.cpp
> BucketSort.cpp

- Algorithms/Searching & Sorting/Binary Search/CPP/Binary_Search_Iter_Recur.cpp
Contains both Iterative and Recursive method for Binary Search. This solves #65
> Binary_Search_Iter_Recur.cpp

- Company Specific Interview Questions/Google/Solutions/Cpp/DNA.cpp
Problem Given:A forensic lab wants to know whether a deceased person’s DNA matches a set of known relatives. It is known that the closest relatives will have most of the DNA matching, and as the relationship becomes farther, the matching genes will be lesser. For this, the DNA pattern of the deceased is given and the DNA pattern of 10 likely relatives are given. Write a program to identify the family of the deceased.
> Solution to The DNA matching problem

- Algorithms/Dynamic Programming/MakeChange.java
- Algorithms/Dynamic Programming/MatrixChainMultiplication.java
Solves Issue #442 
Matrix Chain Multiplication
Make Change
> Added Make Change

- Algorithms/String/dnapatternmatching/dnapattern.py
- Algorithms/String/dnapatternmatching/readme.md
- Algorithms/divide_and_conquer/divide_and_conquer.py
- Algorithms/divide_and_conquer/readme.md
here i have tried to solve the problem using python regular expression method,
**_
> In ths solution we are asked to enter the the common pattern which is getting repeated in the diceased person for maximum number of times.
> That repeating pattern is compared with the dna pattern of all 10 given relatives and the one in which the same pattern occurs for maximum number of time as compare to other 9 relative is the closest relative of diceased person.
_**
> Dna pattern matching and finding closest relative

- Data Structures/Dynamic Array/C/dynamic_array.c
> #565 adding Dynamic and generic Array in C

- Algorithms/Maths/Base Conversion/binary_number/check_multple_of3.c
- Algorithms/Maths/Base Conversion/binary_number/readme.md
- Data Structures/Doubly Linked List/C/doubly_linked_list.c
- Data Structures/Doubly Linked List/C/readme.md
- Data Structures/Stack/C/dynamic_memory_allocation/readme.md
- Data Structures/Stack/C/dynamic_memory_allocation/stack.c
This uses the concept of dynamic memory allocation. it is the efficient way of implement this datastructure.
> doubly linkedlist in C

- Algorithms/Arrays/Bubble_sort/SortBubble.java
> added comments

- Algorithms/Kadane.cpp
> Created Kadane.cpp

- Factorial.c
> Factorial.c

- Algorithms/Maths/Factorial/cpp/factorial.cpp
- Algorithms/Maths/Factorial/python/factorial.py
- Algorithms/Maths/armstrong-number/README.md
- Algorithms/Maths/armstrong-number/armstrong-number.cpp
- Algorithms/Recursion/palindrome/palindrome.cpp
- Algorithms/Recursion/palindrome/palindrome.java
- Algorithms/Recursion/palindrome/palindrome.py
I have added the following files :
1. factorial.py
factorial.cpp
2. armstrong-number.cpp
3. recursion/palindrome.py
recursion/palindrome.cpp
recursion/palindrome.java
> Created new files  (factorial, armstrong-number,  recursion/palindrome)

- Algorithms/Searching & Sorting/Depth First Search/depth_first_search.cpp
Added C++ version of Depth First Search. Updated the code with necessary comments for better understanding. Solves the issue #660
> Added Depth-First-Search Code in C++

- Algorithms/Searching & Sorting/Breadth-First-Search.cs
Solves https://github.com/fnplus/interview-techdev-guide/issues/661
I couldn't create the folder through Github-Ui
> Added Breadth First Search (Searching Algorithm)

- Data Structures/Disjoint Sets/Java/DisjointSets.java
- Data Structures/Disjoint Sets/Python/DisjointSets.py
> added Java implementation of disjoint set
